#!/usr/bin/env python3
r"""
Analysis of the nested Llama 3.3 70B revision campaign:

  output/revision-nested-comm   - communication baseline (+pre-decision beliefs,
                                  messages excluded from the belief prompt)
  output/revision-nested-surv   - clean surveillance (+same belief elicitation)
  output/revision-nested-style  - codedness-induction control (style instruction,
                                  no monitoring framing)
  output/revision-nested-decoded-replay - decoded surveilled messages replayed
  output/revision-nested-raw-replay     - raw surveilled messages replayed

All arms share grid and seed (10 countries x 50 periods, n=25, seed 5150), so
cells are nested by construction. Writes paper/tables/stats_nested.tex.

Usage: uv run python analysis/nested_campaign_checks.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parent.parent
MODEL_DIR = "meta-llama--llama-3.3-70b-instruct"
OUT = ROOT / "paper" / "tables" / "stats_nested.tex"

ARMS = {
    "comm": ROOT / "output" / "revision-nested-comm" / MODEL_DIR / "experiment_comm_log.json",
    "surv": ROOT / "output" / "revision-nested-surv" / MODEL_DIR / "experiment_comm_log.json",
    "style": ROOT / "output" / "revision-nested-style" / MODEL_DIR / "experiment_comm_log.json",
    "decoded": ROOT / "output" / "revision-nested-decoded-replay" / MODEL_DIR / "experiment_comm_log.json",
    "rawreplay": ROOT / "output" / "revision-nested-raw-replay" / MODEL_DIR / "experiment_comm_log.json",
}

CODED_PAT = re.compile(
    r"walls? (?:are|is) crack|ground (?:is )?shift|heads? down|feels? different|"
    r"weather|wind|storm|season|harvest|garden|seeds?\b|roots?\b|tide|current\b",
    re.I,
)
DIRECT_PAT = re.compile(r"regime|security forces|police|military|street|protest|uprising", re.I)

KEY = ["country", "period", "theta", "z", "benefit", "theta_star"]


def load(path: Path):
    if not path.exists():
        return None, None, None
    data = json.loads(path.read_text())
    rows, msgs, beliefs = [], [], []
    for e in data:
        rows.append(
            {
                "country": e.get("country"),
                "period": e.get("period"),
                "theta": round(float(e["theta"]), 6),
                "z": round(float(e.get("z", np.nan)), 6),
                "benefit": e.get("benefit"),
                "theta_star": e.get("theta_star"),
                "jf": e.get("join_fraction_valid", e.get("join_fraction")),
            }
        )
        for ag in e.get("agents", []):
            if ag.get("api_error"):
                continue
            msg = ag.get("message_sent") or ""
            if msg.strip():
                msgs.append(msg)
            bp = ag.get("belief_pre")
            sp = ag.get("second_order_belief_pre")
            if bp is not None or sp is not None:
                beliefs.append({"belief_pre": bp, "sob_pre": sp})
    cells = pd.DataFrame(rows).dropna(subset=["jf"]).groupby(KEY, as_index=False)["jf"].mean()
    return cells, msgs, pd.DataFrame(beliefs)


def paired(a: pd.DataFrame, b: pd.DataFrame):
    m = a.merge(b, on=KEY, suffixes=("_a", "_b"))
    d = m["jf_b"] - m["jf_a"]
    t, p = stats.ttest_1samp(d, 0.0)
    return len(m), float(d.mean()) * 100, float(t), float(p)


def fmt_p(p: float) -> str:
    return "$<$0.001" if p < 0.001 else f"= {p:.3f}"


def main() -> None:
    arms = {k: load(v) for k, v in ARMS.items()}
    comm_cells, comm_msgs, comm_bel = arms["comm"]
    if comm_cells is None:
        print("comm arm log not found; nothing to do")
        return
    lines = ["% Auto-generated by analysis/nested_campaign_checks.py -- do not edit."]

    def emit(name: str, val: str) -> None:
        lines.append(f"\\providecommand{{\\{name}}}{{{val}}}")

    emit("NestedCommMeanJoinPct", f"{comm_cells['jf'].mean()*100:.1f}\\%")

    for arm, prefix in (("surv", "NestedSurv"), ("style", "NestedStyle"),
                        ("decoded", "NestedDecoded"), ("rawreplay", "NestedRawReplay")):
        cells = arms[arm][0]
        if cells is None:
            print(f"  [skip] {arm}: no log yet")
            continue
        n, dpp, t, p = paired(comm_cells, cells)
        emit(f"{prefix}N", str(n))
        emit(f"{prefix}DeltaPP", f"{dpp:+.1f}")
        emit(f"{prefix}DeltaAbsPP", f"{abs(dpp):.1f}")
        emit(f"{prefix}T", f"{t:+.2f}")
        emit(f"{prefix}PText", fmt_p(p))
        emit(f"{prefix}MeanJoinPct", f"{cells['jf'].mean()*100:.1f}\\%")
        print(f"  {arm}: N={n} delta={dpp:+.1f}pp t={t:+.2f} p={p:.2g}")

    # decoded vs raw replay (within fixed-messages machinery)
    if arms["decoded"][0] is not None and arms["rawreplay"][0] is not None:
        n, dpp, t, p = paired(arms["rawreplay"][0], arms["decoded"][0])
        emit("NestedDecodeVsRawN", str(n))
        emit("NestedDecodeVsRawDeltaPP", f"{dpp:+.1f}")
        emit("NestedDecodeVsRawPText", fmt_p(p))
        print(f"  decoded-vs-raw: N={n} delta={dpp:+.1f}pp p={p:.2g}")

    # surveillance vs style (does monitoring framing add anything beyond style?)
    if arms["surv"][0] is not None and arms["style"][0] is not None:
        n, dpp, t, p = paired(arms["style"][0], arms["surv"][0])
        emit("NestedSurvVsStyleN", str(n))
        emit("NestedSurvVsStyleDeltaPP", f"{dpp:+.1f}")
        emit("NestedSurvVsStylePText", fmt_p(p))
        print(f"  surv-vs-style: N={n} delta={dpp:+.1f}pp p={p:.2g}")

    # message manipulation check: coded/direct rates per arm
    for arm, prefix in (("comm", "NestedComm"), ("surv", "NestedSurv"), ("style", "NestedStyle")):
        msgs = arms[arm][1]
        if not msgs:
            continue
        emit(f"{prefix}CodedPct", f"{100*sum(bool(CODED_PAT.search(t)) for t in msgs)/len(msgs):.1f}\\%")
        emit(f"{prefix}DirectPct", f"{100*sum(bool(DIRECT_PAT.search(t)) for t in msgs)/len(msgs):.1f}\\%")

    # pre-decision, messages-excluded beliefs: comm vs surv
    bs = arms["surv"][2]
    if comm_bel is not None and bs is not None and len(comm_bel) and len(bs):
        for col, tag in (("belief_pre", "NestedBel"), ("sob_pre", "NestedSOB")):
            a = comm_bel[col].dropna().astype(float)
            b = bs[col].dropna().astype(float)
            if len(a) and len(b):
                t, p = stats.ttest_ind(b, a, equal_var=False)
                emit(f"{tag}CommMean", f"{a.mean():.1f}")
                emit(f"{tag}SurvMean", f"{b.mean():.1f}")
                emit(f"{tag}DeltaPP", f"{b.mean()-a.mean():+.1f}")
                emit(f"{tag}PText", fmt_p(p))
                print(f"  {tag}: comm {a.mean():.1f} surv {b.mean():.1f} p={p:.2g}")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
