#!/usr/bin/env python3
r"""
Receiver-rationale dictionary audit and theta-tercile heterogeneity for the
clean prompt-isolation surveillance contrast (primary model).

Reads JSON logs from output/, writes paper/tables/stats_rationale.tex
(\providecommand macros only; \input from paper.tex).

Usage: uv run python analysis/rationale_theta_checks.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "paper" / "tables" / "stats_rationale.tex"
PRIMARY = "mistralai--mistral-small-creative"

BASE_LOG = ROOT / "output" / PRIMARY / "experiment_comm_log.json"
SURV_LOG = ROOT / "output" / "prompt-isolation-surveillance" / PRIMARY / "experiment_comm_log.json"

# High-precision stems: explicit references to monitoring/surveillance by the
# receiver. "watch" is excluded as too ambiguous ("watching the situation").
SURV_TERMS = re.compile(
    r"surveil|monitor|informant|intercept|\bspy\b|spied|spying|wiretap|eavesdrop|secret police",
    re.I,
)
FEAR_TERMS = re.compile(
    r"\brisk|danger|afraid|fear|caution|careful|\bsafe|arrest|punish|consequence|reprisal|crackdown",
    re.I,
)
PEER_TERMS = re.compile(r"contact|message|trusted|\bpeer|others (?:are|say|seem|sound)", re.I)
WEAK_TERMS = re.compile(r"\bweak|crack|fractur|unstable|collaps|defect|falter|crumbl", re.I)


def load_cells(path: Path) -> tuple[pd.DataFrame, list[str]]:
    data = json.loads(path.read_text())
    rows, rationales = [], []
    for e in data:
        rows.append(
            {
                "country": e.get("country"),
                "period": e.get("period"),
                "theta": round(float(e["theta"]), 6),
                "z": round(float(e.get("z", np.nan)), 6),
                "benefit": e.get("benefit"),
                "theta_star": e.get("theta_star"),
                "jf": e.get("join_fraction_valid", e.get("join_fraction")),
            }
        )
        for ag in e.get("agents", []):
            if ag.get("api_error"):
                continue
            dec = str(ag.get("decision", "")).strip().upper()
            if dec not in ("JOIN", "STAY"):
                continue
            txt = ag.get("reasoning")
            if isinstance(txt, str) and txt.strip():
                rationales.append(txt)
    return pd.DataFrame(rows), rationales


def rate(rationales: list[str], pat: re.Pattern) -> float:
    if not rationales:
        return float("nan")
    return sum(bool(pat.search(t)) for t in rationales) / len(rationales)


def two_prop_z(k1: int, n1: int, k2: int, n2: int) -> tuple[float, float]:
    p_pool = (k1 + k2) / (n1 + n2)
    se = np.sqrt(p_pool * (1 - p_pool) * (1 / n1 + 1 / n2))
    z = (k1 / n1 - k2 / n2) / se
    p = 2 * (1 - stats.norm.cdf(abs(z)))
    return float(z), float(p)


def fmt_p(p: float) -> str:
    return "$<$0.001" if p < 0.001 else f"= {p:.3f}"


def main() -> None:
    base_cells, base_rat = load_cells(BASE_LOG)
    surv_cells, surv_rat = load_cells(SURV_LOG)

    # ── Matched-cell deltas by theta tercile ──
    key = ["country", "period", "theta", "z", "benefit", "theta_star"]
    b = base_cells.dropna(subset=["jf"]).groupby(key, as_index=False)["jf"].mean()
    s = surv_cells.dropna(subset=["jf"]).groupby(key, as_index=False)["jf"].mean()
    m = b.merge(s, on=key, suffixes=("_b", "_s"))
    m["delta"] = m["jf_s"] - m["jf_b"]
    n_matched = len(m)
    m["tercile"] = pd.qcut(m["theta"], 3, labels=["low", "mid", "high"])

    lines = ["% Auto-generated by analysis/rationale_theta_checks.py -- do not edit."]
    lines.append(f"\\providecommand{{\\TercileNMatched}}{{{n_matched}}}")
    for lab in ("low", "mid", "high"):
        d = m.loc[m["tercile"] == lab, "delta"]
        t, p = stats.ttest_1samp(d, 0.0)
        cap = lab.capitalize()
        lines.append(f"\\providecommand{{\\Tercile{cap}DeltaPP}}{{{d.mean()*100:+.1f}}}")
        lines.append(f"\\providecommand{{\\Tercile{cap}N}}{{{len(d)}}}")
        lines.append(f"\\providecommand{{\\Tercile{cap}PText}}{{{fmt_p(p)}}}")
        lo = m.loc[m["tercile"] == lab, "theta"].min()
        hi = m.loc[m["tercile"] == lab, "theta"].max()
        lines.append(f"\\providecommand{{\\Tercile{cap}Range}}{{[{lo:+.2f}, {hi:+.2f}]}}")

    # ── Receiver rationale dictionary audit ──
    lines.append(f"\\providecommand{{\\RatNBase}}{{{len(base_rat):,}}}".replace(",", "{,}"))
    lines.append(f"\\providecommand{{\\RatNSurv}}{{{len(surv_rat):,}}}".replace(",", "{,}"))
    for name, pat in (
        ("SurvInfer", SURV_TERMS),
        ("Fear", FEAR_TERMS),
        ("Peer", PEER_TERMS),
        ("Weak", WEAK_TERMS),
    ):
        rb, rs = rate(base_rat, pat), rate(surv_rat, pat)
        lines.append(f"\\providecommand{{\\Rat{name}BasePct}}{{{rb*100:.1f}\\%}}")
        lines.append(f"\\providecommand{{\\Rat{name}SurvPct}}{{{rs*100:.1f}\\%}}")
        kb = round(rb * len(base_rat))
        ks = round(rs * len(surv_rat))
        z, p = two_prop_z(ks, len(surv_rat), kb, len(base_rat))
        lines.append(f"\\providecommand{{\\Rat{name}Z}}{{{z:+.2f}}}")
        lines.append(f"\\providecommand{{\\Rat{name}PText}}{{{fmt_p(p)}}}")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(lines)} lines)")
    print(f"Matched cells: {n_matched}")
    for lab in ("low", "mid", "high"):
        d = m.loc[m["tercile"] == lab, "delta"]
        print(f"  {lab}: mean delta {d.mean()*100:+.1f} pp (n={len(d)})")
    for name, pat in (("surv", SURV_TERMS), ("fear", FEAR_TERMS), ("peer", PEER_TERMS), ("weak", WEAK_TERMS)):
        print(f"  {name}: base {rate(base_rat, pat)*100:.1f}% surv {rate(surv_rat, pat)*100:.1f}%")


if __name__ == "__main__":
    main()
